<a href="https://colab.research.google.com/github/Rohan-1103/Data-Science/blob/main/DL/keras_hyperparameter_tuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [139]:
import pandas as pd
import numpy as np

### Reading the data

In [140]:
df = pd.read_csv('diabetes.csv')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

### Checking effect of each feature on Outcome column

In [141]:
df.corr()["Outcome"]

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

### X and Y
### Applying train test split

In [142]:
x = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [143]:
x

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

### Data Preprocessing

In [144]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [145]:
x = scaler.fit_transform(x)

In [146]:
x.shape

(768, 8)

### Train test split

In [147]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=43)

### Neural Network Model

In [148]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Input, Dropout

In [149]:
model = Sequential()

In [150]:
model.add(Input(shape=(8,)))   # 👈 define input here
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [151]:
model.fit(x_train, y_train, batch_size = 32, epochs=50, validation_data=(x_test, y_test))

Epoch 1/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 52ms/step - accuracy: 0.4121 - loss: 0.7397 - val_accuracy: 0.5519 - val_loss: 0.6935
Epoch 2/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5586 - loss: 0.6704 - val_accuracy: 0.6429 - val_loss: 0.6429
Epoch 3/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6840 - loss: 0.6199 - val_accuracy: 0.7078 - val_loss: 0.6045
Epoch 4/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7410 - loss: 0.5831 - val_accuracy: 0.7338 - val_loss: 0.5795
Epoch 5/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7524 - loss: 0.5541 - val_accuracy: 0.7532 - val_loss: 0.5620
Epoch 6/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.5330 - val_accuracy: 0.7597 - val_loss: 0.5489
Epoch 7/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.5169 - val_accuracy: 0.7662 - val_loss: 0.5401
Epoch 8/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.5035 - val_accuracy: 0.7727 - val_loss: 0.5326
Epoch 9/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7622 - loss: 0.4923 - val_accuracy: 0.7727 - val_loss: 0.5311
Epoch 10/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.4836 - val_accuracy: 0.7792 - val_loss: 0.5275
Epoch 11/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4766 - val_accuracy: 0.7857 - val_loss: 0.5259
Epoch 12/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4709 - val_accuracy: 0.7857 - val_loss: 0.5263
Epoch 13/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4662 - val_accuracy: 0.7857 - val_loss: 0.5254
Epoch 14/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4625 - val_accuracy: 0.7857 - val_loss: 0.5269
Epoch 15/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4591 - val_accuracy: 0.7857 - val_loss: 0.5267
Epoch 16/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4561 - val_accuracy: 0.7857 - val_loss: 0.5247
Epoch 17/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4538 - val_accuracy: 0.7857 - val_loss: 0.5261
Epoch 18/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4517 - val_accuracy: 0.7857 - val_loss: 0.5264
Epoch 19/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4495 - val_accuracy: 0.7792 - val_loss: 0.5271
Epoch 20/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4477 - val_accuracy: 0.7727 - val_loss: 0.5285
Epoch 21/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4458 - val_accuracy: 0.7792 - val_loss: 0.5265
Epoch 22/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4444 - val_accuracy: 0.7662 - val_loss: 0.5280
Epoch 23/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4426 - val_accuracy: 0.7662 - val_loss: 0.5279
Epoch 24/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4417 - val_accuracy: 0.7662 - val_loss: 0.5287
Epoch 25/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4397 - val_accuracy: 0.7597 - val_loss: 0.5284
Epoch 26/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4387 - val_accuracy: 0.7662 - val_loss: 0.5280
Epoch 27/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4374 - val_accuracy: 0.7597 - val_loss: 0.5297
Epoch 28/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4363 - val_accuracy: 0.7597 - val_loss: 0.5312
Epoch 29/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4350 - val_accuracy: 0.7662 - val_loss: 0.5320
Epoch 30/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4343 - val_accuracy: 0.7662 - val_loss: 0.5335
Epoch 31/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4335 - val_accuracy: 0.7597 - val_loss: 0.5344
Epoch 32/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4332 - val_accuracy: 0.7597 - val_loss: 0.5363
Epoch 33/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4324 - val_accuracy: 0.7662 - val_loss: 0.5337
Epoch 34/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4314 - val_accuracy: 0.7597 - val_loss: 0.5334
Epoch 35/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4299 - val_accuracy: 0.7597 - val_loss: 0.5331
Epoch 36/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4294 - val_accuracy: 0.7662 - val_loss: 0.5334
Epoch 37/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4285 - val_accuracy: 0.7597 - val_loss: 0.5319
Epoch 38/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4276 - val_accuracy: 0.7662 - val_loss: 0.5324
Epoch 39/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4280 - val_accuracy: 0.7597 - val_loss: 0.5341
Epoch 40/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4268 - val_accuracy: 0.7597 - val_loss: 0.5329
Epoch 41/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4260 - val_accuracy: 0.7597 - val_loss: 0.5305
Epoch 42/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4257 - val_accuracy: 0.7597 - val_loss: 0.5334
Epoch 43/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4244 - val_accuracy: 0.7597 - val_loss: 0.5325
Epoch 44/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4243 - val_accuracy: 0.7597 - val_loss: 0.5331
Epoch 45/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4238 - val_accuracy: 0.7662 - val_loss: 0.5334
Epoch 46/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4228 - val_accuracy: 0.7597 - val_loss: 0.5314
Epoch 47/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4230 - val_accuracy: 0.7468 - val_loss: 0.5314
Epoch 48/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4221 - val_accuracy: 0.7532 - val_loss: 0.5316
Epoch 49/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4215 - val_accuracy: 0.7532 - val_loss: 0.5316
Epoch 50/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4212 - val_accuracy: 0.7468 - val_loss: 0.5300

## Problem:
 - Have to decide layers.
 - Have to decide nodes.
 - Have to decide activation.
 - Have to decide loss.
 - Have to decide optimizer.

 ## Solution:
  - Automate using Keras-Tuner performing hyperparameter tuning

In [152]:
!pip install keras-tuner
import kerastuner as kt

Requirement already satisfied: keras-tuner in /usr/local/lib/python3.12/dist-packages (1.4.8)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Requirement already satisfied: kt-legacy in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.0.5)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.78.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.2.25)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)

### Steps:
  1. Make a function.
  2. Make a tuner object.
  3. Pass tuner object to function.

### 1. Make a function - build_model(hp)
 - To tune best optimizer

In [153]:
# Selecting best optimizer
def build_model(hp):
  model = Sequential()
  model.add(Input(shape=(8, )))
  model.add(Dense(32, activation='relu'))
  model.add(Dense(1, activation='sigmoid'))

  optimizer = hp.Choice('optimizer', values = ['adam', 'sgd', 'rmsprop', 'adadelta'])
  model.compile(optimizer=optimizer, loss = 'binary_crossentropy', metrics=['accuracy'])

  return model

### Make a tuner object and pass it to Function via RandomSearch

In [154]:
tuner = kt.RandomSearch(build_model, objective='val_accuracy', max_trials=5)

Reloading Tuner from ./untitled_project/tuner0.json

In [155]:
tuner.search(x_train, y_train, epochs=5, validation_data=(x_test, y_test))

In [156]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'adam'}

In [157]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [158]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [159]:
model.fit(x_train, y_train, batch_size=32, epochs=100, initial_epoch=6, validation_data=(x_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - accuracy: 0.7541 - loss: 0.5444 - val_accuracy: 0.7468 - val_loss: 0.5388
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7736 - loss: 0.5182 - val_accuracy: 0.7468 - val_loss: 0.5211
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7818 - loss: 0.4999 - val_accuracy: 0.7597 - val_loss: 0.5113
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.7834 - loss: 0.4877 - val_accuracy: 0.7662 - val_loss: 0.5063
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.7818 - loss: 0.4787 - val_accuracy: 0.7662 - val_loss: 0.5016
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.7834 - loss: 0.4734 - val_accuracy: 0.7662 - val_loss: 0.4994
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7850 - loss: 0.4676 - val_accuracy: 0.7662 - val_loss: 0.4980
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7883 - loss: 0.4641 - val_accuracy: 0.7727 - val_loss: 0.4970
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7850 - loss: 0.4607 - val_accuracy: 0.7857 - val_loss: 0.4955
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7818 - loss: 0.4573 - val_accuracy: 0.7792 - val_loss: 0.4965
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7834 - loss: 0.4546 - val_accuracy: 0.7792 - val_loss: 0.4957
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.7850 - loss: 0.4534 - val_accuracy: 0.7792 - val_loss: 0.4952
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7866 - loss: 0.4514 - val_accuracy: 0.7792 - val_loss: 0.4958
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.7899 - loss: 0.4500 - val_accuracy: 0.7857 - val_loss: 0.4957
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.7899 - loss: 0.4479 - val_accuracy: 0.7857 - val_loss: 0.4975
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7915 - loss: 0.4470 - val_accuracy: 0.7792 - val_loss: 0.4991
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4452 - val_accuracy: 0.7857 - val_loss: 0.4996
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4450 - val_accuracy: 0.7792 - val_loss: 0.4975
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4435 - val_accuracy: 0.7857 - val_loss: 0.4992
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4422 - val_accuracy: 0.7922 - val_loss: 0.4988
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4410 - val_accuracy: 0.7987 - val_loss: 0.4988
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4419 - val_accuracy: 0.7857 - val_loss: 0.4991
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4398 - val_accuracy: 0.7792 - val_loss: 0.5007
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4389 - val_accuracy: 0.7922 - val_loss: 0.5029
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4381 - val_accuracy: 0.7922 - val_loss: 0.5041
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4372 - val_accuracy: 0.7857 - val_loss: 0.5048
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4365 - val_accuracy: 0.7727 - val_loss: 0.5057
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4364 - val_accuracy: 0.7727 - val_loss: 0.5061
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4349 - val_accuracy: 0.7597 - val_loss: 0.5060
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4344 - val_accuracy: 0.7662 - val_loss: 0.5065
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4337 - val_accuracy: 0.7532 - val_loss: 0.5085
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4332 - val_accuracy: 0.7532 - val_loss: 0.5097
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4323 - val_accuracy: 0.7662 - val_loss: 0.5087
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4318 - val_accuracy: 0.7403 - val_loss: 0.5108
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4309 - val_accuracy: 0.7662 - val_loss: 0.5099
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4305 - val_accuracy: 0.7662 - val_loss: 0.5098
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4299 - val_accuracy: 0.7727 - val_loss: 0.5108
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4303 - val_accuracy: 0.7532 - val_loss: 0.5121
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4283 - val_accuracy: 0.7662 - val_loss: 0.5103
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4286 - val_accuracy: 0.7727 - val_loss: 0.5091
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4276 - val_accuracy: 0.7662 - val_loss: 0.5104
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4273 - val_accuracy: 0.7532 - val_loss: 0.5111
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4265 - val_accuracy: 0.7662 - val_loss: 0.5128
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4259 - val_accuracy: 0.7597 - val_loss: 0.5123
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4254 - val_accuracy: 0.7597 - val_loss: 0.5142
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4252 - val_accuracy: 0.7532 - val_loss: 0.5126
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4248 - val_accuracy: 0.7532 - val_loss: 0.5108
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4242 - val_accuracy: 0.7597 - val_loss: 0.5099
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4236 - val_accuracy: 0.7597 - val_loss: 0.5133
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4233 - val_accuracy: 0.7532 - val_loss: 0.5159
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4229 - val_accuracy: 0.7532 - val_loss: 0.5150
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4222 - val_accuracy: 0.7532 - val_loss: 0.5166
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7980 - loss: 0.4216 - val_accuracy: 0.7468 - val_loss: 0.5177
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4216 - val_accuracy: 0.7532 - val_loss: 0.5162
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4213 - val_accuracy: 0.7532 - val_loss: 0.5186
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4206 - val_accuracy: 0.7403 - val_loss: 0.5225
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4204 - val_accuracy: 0.7532 - val_loss: 0.5242
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4200 - val_accuracy: 0.7532 - val_loss: 0.5247
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4189 - val_accuracy: 0.7532 - val_loss: 0.5234
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4188 - val_accuracy: 0.7532 - val_loss: 0.5249
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4182 - val_accuracy: 0.7468 - val_loss: 0.5209
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4175 - val_accuracy: 0.7468 - val_loss: 0.5218
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4172 - val_accuracy: 0.7468 - val_loss: 0.5229
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4166 - val_accuracy: 0.7468 - val_loss: 0.5205
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4162 - val_accuracy: 0.7468 - val_loss: 0.5215
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4160 - val_accuracy: 0.7468 - val_loss: 0.5225
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4155 - val_accuracy: 0.7403 - val_loss: 0.5223
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4150 - val_accuracy: 0.7403 - val_loss: 0.5231
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4147 - val_accuracy: 0.7662 - val_loss: 0.5210
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4146 - val_accuracy: 0.7468 - val_loss: 0.5231
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4139 - val_accuracy: 0.7532 - val_loss: 0.5241
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4137 - val_accuracy: 0.7532 - val_loss: 0.5238
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4137 - val_accuracy: 0.7597 - val_loss: 0.5218
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4129 - val_accuracy: 0.7532 - val_loss: 0.5266
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4129 - val_accuracy: 0.7338 - val_loss: 0.5289
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4120 - val_accuracy: 0.7338 - val_loss: 0.5265
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4116 - val_accuracy: 0.7532 - val_loss: 0.5253
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4110 - val_accuracy: 0.7532 - val_loss: 0.5246
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4111 - val_accuracy: 0.7468 - val_loss: 0.5247
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8094 - loss: 0.4105 - val_accuracy: 0.7468 - val_loss: 0.5263
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8111 - loss: 0.4102 - val_accuracy: 0.7403 - val_loss: 0.5261
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8127 - loss: 0.4100 - val_accuracy: 0.7403 - val_loss: 0.5284
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8111 - loss: 0.4095 - val_accuracy: 0.7403 - val_loss: 0.5289
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8160 - loss: 0.4092 - val_accuracy: 0.7403 - val_loss: 0.5282
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8176 - loss: 0.4090 - val_accuracy: 0.7597 - val_loss: 0.5251
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8192 - loss: 0.4081 - val_accuracy: 0.7468 - val_loss: 0.5273
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8192 - loss: 0.4083 - val_accuracy: 0.7597 - val_loss: 0.5295
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8192 - loss: 0.4072 - val_accuracy: 0.7468 - val_loss: 0.5244
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.4071 - val_accuracy: 0.7468 - val_loss: 0.5235
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.4068 - val_accuracy: 0.7468 - val_loss: 0.5225
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8176 - loss: 0.4066 - val_accuracy: 0.7468 - val_loss: 0.5236
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.4061 - val_accuracy: 0.7468 - val_loss: 0.5241
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.4060 - val_accuracy: 0.7468 - val_loss: 0.5235
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.4059 - val_accuracy: 0.7468 - val_loss: 0.5256

- To tune best number of neurons

In [160]:
def build_model(hp):
  model = Sequential()

  units = hp.Int('units', min_value = 8, max_value = 128, step=8)

  model.add(Input(shape=(8, )))
  model.add(Dense(units = units, activation='relu'))
  model.add(Dense(1, activation='sigmoid'))

  model.compile(optimizer='rmsprop',  loss='binary_crossentropy', metrics=['accuracy'])

  return model

In [161]:
tuner = kt.RandomSearch(build_model, objective='val_accuracy', max_trials=5, directory='mydir', project_name = 'Hyperparameter Tune')

Reloading Tuner from mydir/Hyperparameter Tune/tuner0.json

In [162]:
tuner.search(x_train, y_train, epochs = 5, validation_data = (x_test, y_test))

In [163]:
tuner.get_best_hyperparameters()[0].values

{'units': 80}

In [164]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [165]:
model.fit(x_train, y_train, batch_size=32, epochs=100, initial_epoch=6, validation_data=(x_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step - accuracy: 0.7720 - loss: 0.4703 - val_accuracy: 0.7922 - val_loss: 0.5143
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4606 - val_accuracy: 0.7922 - val_loss: 0.5123
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4560 - val_accuracy: 0.7922 - val_loss: 0.5149
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4522 - val_accuracy: 0.7922 - val_loss: 0.5135
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4497 - val_accuracy: 0.7857 - val_loss: 0.5128
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4464 - val_accuracy: 0.7922 - val_loss: 0.5149
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4452 - val_accuracy: 0.7792 - val_loss: 0.5174
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4428 - val_accuracy: 0.7662 - val_loss: 0.5200
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4429 - val_accuracy: 0.7727 - val_loss: 0.5221
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4414 - val_accuracy: 0.7857 - val_loss: 0.5212
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4404 - val_accuracy: 0.7857 - val_loss: 0.5176
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4382 - val_accuracy: 0.7727 - val_loss: 0.5177
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4375 - val_accuracy: 0.7857 - val_loss: 0.5181
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4369 - val_accuracy: 0.7857 - val_loss: 0.5198
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7899 - loss: 0.4354 - val_accuracy: 0.7922 - val_loss: 0.5191
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4346 - val_accuracy: 0.7792 - val_loss: 0.5199
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4338 - val_accuracy: 0.7727 - val_loss: 0.5214
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4331 - val_accuracy: 0.7857 - val_loss: 0.5220
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4323 - val_accuracy: 0.7792 - val_loss: 0.5216
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4314 - val_accuracy: 0.7662 - val_loss: 0.5236
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4305 - val_accuracy: 0.7727 - val_loss: 0.5245
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4300 - val_accuracy: 0.7792 - val_loss: 0.5265
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4290 - val_accuracy: 0.7857 - val_loss: 0.5233
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4281 - val_accuracy: 0.7922 - val_loss: 0.5201
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4267 - val_accuracy: 0.7922 - val_loss: 0.5186
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4264 - val_accuracy: 0.7857 - val_loss: 0.5168
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4255 - val_accuracy: 0.7792 - val_loss: 0.5189
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4252 - val_accuracy: 0.7792 - val_loss: 0.5219
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4246 - val_accuracy: 0.7792 - val_loss: 0.5229
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4244 - val_accuracy: 0.7727 - val_loss: 0.5200
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4238 - val_accuracy: 0.7662 - val_loss: 0.5217
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4221 - val_accuracy: 0.7792 - val_loss: 0.5222
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4220 - val_accuracy: 0.7792 - val_loss: 0.5249
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4213 - val_accuracy: 0.7727 - val_loss: 0.5282
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4209 - val_accuracy: 0.7662 - val_loss: 0.5283
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4204 - val_accuracy: 0.7597 - val_loss: 0.5288
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4195 - val_accuracy: 0.7597 - val_loss: 0.5244
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4189 - val_accuracy: 0.7597 - val_loss: 0.5277
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4184 - val_accuracy: 0.7532 - val_loss: 0.5271
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4179 - val_accuracy: 0.7532 - val_loss: 0.5296
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4176 - val_accuracy: 0.7662 - val_loss: 0.5319
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4172 - val_accuracy: 0.7597 - val_loss: 0.5280
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4167 - val_accuracy: 0.7597 - val_loss: 0.5269
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4156 - val_accuracy: 0.7468 - val_loss: 0.5296
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8176 - loss: 0.4153 - val_accuracy: 0.7532 - val_loss: 0.5289
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8176 - loss: 0.4147 - val_accuracy: 0.7597 - val_loss: 0.5267
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8143 - loss: 0.4138 - val_accuracy: 0.7597 - val_loss: 0.5265
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8208 - loss: 0.4137 - val_accuracy: 0.7532 - val_loss: 0.5277
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8160 - loss: 0.4133 - val_accuracy: 0.7532 - val_loss: 0.5262
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8176 - loss: 0.4127 - val_accuracy: 0.7597 - val_loss: 0.5238
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8160 - loss: 0.4120 - val_accuracy: 0.7532 - val_loss: 0.5231
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8225 - loss: 0.4117 - val_accuracy: 0.7532 - val_loss: 0.5253
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8160 - loss: 0.4110 - val_accuracy: 0.7532 - val_loss: 0.5215
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8192 - loss: 0.4102 - val_accuracy: 0.7597 - val_loss: 0.5202
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4098 - val_accuracy: 0.7532 - val_loss: 0.5242
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4089 - val_accuracy: 0.7403 - val_loss: 0.5275
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.4087 - val_accuracy: 0.7532 - val_loss: 0.5259
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.4083 - val_accuracy: 0.7468 - val_loss: 0.5287
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.4079 - val_accuracy: 0.7468 - val_loss: 0.5293
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4071 - val_accuracy: 0.7468 - val_loss: 0.5253
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.4066 - val_accuracy: 0.7468 - val_loss: 0.5283
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.4068 - val_accuracy: 0.7403 - val_loss: 0.5261
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.4054 - val_accuracy: 0.7468 - val_loss: 0.5287
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.4048 - val_accuracy: 0.7403 - val_loss: 0.5272
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4048 - val_accuracy: 0.7532 - val_loss: 0.5298
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.4044 - val_accuracy: 0.7403 - val_loss: 0.5295
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.4034 - val_accuracy: 0.7338 - val_loss: 0.5320
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.4031 - val_accuracy: 0.7468 - val_loss: 0.5308
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.4026 - val_accuracy: 0.7403 - val_loss: 0.5286
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.4018 - val_accuracy: 0.7403 - val_loss: 0.5235
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.4019 - val_accuracy: 0.7468 - val_loss: 0.5237
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.4006 - val_accuracy: 0.7468 - val_loss: 0.5276
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.4012 - val_accuracy: 0.7468 - val_loss: 0.5295
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.4003 - val_accuracy: 0.7338 - val_loss: 0.5327
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3998 - val_accuracy: 0.7338 - val_loss: 0.5292
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3991 - val_accuracy: 0.7403 - val_loss: 0.5275
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3992 - val_accuracy: 0.7338 - val_loss: 0.5291
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3985 - val_accuracy: 0.7338 - val_loss: 0.5299
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3975 - val_accuracy: 0.7403 - val_loss: 0.5270
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3972 - val_accuracy: 0.7338 - val_loss: 0.5280
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3968 - val_accuracy: 0.7338 - val_loss: 0.5303
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3964 - val_accuracy: 0.7338 - val_loss: 0.5304
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3968 - val_accuracy: 0.7273 - val_loss: 0.5338
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3950 - val_accuracy: 0.7403 - val_loss: 0.5313
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3954 - val_accuracy: 0.7338 - val_loss: 0.5318
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3949 - val_accuracy: 0.7273 - val_loss: 0.5301
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3947 - val_accuracy: 0.7273 - val_loss: 0.5313
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8290 - loss: 0.3940 - val_accuracy: 0.7273 - val_loss: 0.5301
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3935 - val_accuracy: 0.7273 - val_loss: 0.5311
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3934 - val_accuracy: 0.7403 - val_loss: 0.5305
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3922 - val_accuracy: 0.7403 - val_loss: 0.5300
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3922 - val_accuracy: 0.7338 - val_loss: 0.5324
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3913 - val_accuracy: 0.7338 - val_loss: 0.5330
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3915 - val_accuracy: 0.7338 - val_loss: 0.5309

### To tune the number of hidden layers

In [166]:
def build_model(hp):
  model = Sequential()

  model.add(Input(shape=(8, )))
  model.add(Dense(72, activation = 'relu'))

  for i in range(hp.Int('num_layers', min_value = 1, max_value = 10)):
    model.add(Dense(72, activation='relu'))

  model.add(Dense(1, activation = 'sigmoid'))
  model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

  return model

In [167]:
tuner = kt.RandomSearch(build_model, objective='val_accuracy', max_trials=3, directory = 'mydir', project_name='num_layers')

Reloading Tuner from mydir/num_layers/tuner0.json

In [168]:
tuner.search(x_train, y_train, epochs=5, validation_data=(x_test, y_test))

In [169]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 2}

In [170]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [171]:
model.fit(x_train, y_train, epochs = 100, initial_epoch=6, validation_data=(x_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 61ms/step - accuracy: 0.7769 - loss: 0.4672 - val_accuracy: 0.7727 - val_loss: 0.4873
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4470 - val_accuracy: 0.7662 - val_loss: 0.5005
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4390 - val_accuracy: 0.7597 - val_loss: 0.5059
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4375 - val_accuracy: 0.7532 - val_loss: 0.5145
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4274 - val_accuracy: 0.7338 - val_loss: 0.5103
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4233 - val_accuracy: 0.7597 - val_loss: 0.5344
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4178 - val_accuracy: 0.7338 - val_loss: 0.5193
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4078 - val_accuracy: 0.7338 - val_loss: 0.5322
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8208 - loss: 0.4136 - val_accuracy: 0.7208 - val_loss: 0.5298
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8225 - loss: 0.4038 - val_accuracy: 0.7208 - val_loss: 0.5256
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8160 - loss: 0.3973 - val_accuracy: 0.7468 - val_loss: 0.5491
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8274 - loss: 0.3949 - val_accuracy: 0.7143 - val_loss: 0.5419
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8241 - loss: 0.3884 - val_accuracy: 0.7273 - val_loss: 0.5589
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8306 - loss: 0.3839 - val_accuracy: 0.7273 - val_loss: 0.5383
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8371 - loss: 0.3806 - val_accuracy: 0.7338 - val_loss: 0.5462
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8322 - loss: 0.3742 - val_accuracy: 0.7143 - val_loss: 0.5548
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8355 - loss: 0.3717 - val_accuracy: 0.6883 - val_loss: 0.5825
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8306 - loss: 0.3696 - val_accuracy: 0.6948 - val_loss: 0.5775
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8485 - loss: 0.3625 - val_accuracy: 0.7338 - val_loss: 0.5669
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3614 - val_accuracy: 0.7078 - val_loss: 0.5568
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8550 - loss: 0.3532 - val_accuracy: 0.7208 - val_loss: 0.5745
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3493 - val_accuracy: 0.7013 - val_loss: 0.6493
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3412 - val_accuracy: 0.7273 - val_loss: 0.5880
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3373 - val_accuracy: 0.7208 - val_loss: 0.5940
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8632 - loss: 0.3329 - val_accuracy: 0.7338 - val_loss: 0.6347
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8632 - loss: 0.3293 - val_accuracy: 0.7208 - val_loss: 0.6046
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8599 - loss: 0.3247 - val_accuracy: 0.6948 - val_loss: 0.6336
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8681 - loss: 0.3183 - val_accuracy: 0.7078 - val_loss: 0.6491
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.3088 - val_accuracy: 0.6883 - val_loss: 0.6586
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8697 - loss: 0.3074 - val_accuracy: 0.7013 - val_loss: 0.6779
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8697 - loss: 0.3014 - val_accuracy: 0.7078 - val_loss: 0.5988
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8811 - loss: 0.3015 - val_accuracy: 0.6753 - val_loss: 0.7238
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8827 - loss: 0.2900 - val_accuracy: 0.7143 - val_loss: 0.6277
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8795 - loss: 0.2870 - val_accuracy: 0.6948 - val_loss: 0.6387
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8876 - loss: 0.2783 - val_accuracy: 0.7013 - val_loss: 0.6777
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.2767 - val_accuracy: 0.7013 - val_loss: 0.7190
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8795 - loss: 0.2689 - val_accuracy: 0.7143 - val_loss: 0.6833
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9007 - loss: 0.2610 - val_accuracy: 0.7208 - val_loss: 0.7082
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8876 - loss: 0.2569 - val_accuracy: 0.7338 - val_loss: 0.6645
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8941 - loss: 0.2609 - val_accuracy: 0.7013 - val_loss: 0.6965
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8941 - loss: 0.2522 - val_accuracy: 0.7273 - val_loss: 0.6615
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2430 - val_accuracy: 0.7143 - val_loss: 0.6953
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9072 - loss: 0.2369 - val_accuracy: 0.7013 - val_loss: 0.7078
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9202 - loss: 0.2365 - val_accuracy: 0.7143 - val_loss: 0.7342
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9202 - loss: 0.2272 - val_accuracy: 0.7078 - val_loss: 0.7987
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9072 - loss: 0.2236 - val_accuracy: 0.7273 - val_loss: 0.7502
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9088 - loss: 0.2123 - val_accuracy: 0.6948 - val_loss: 0.8273
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9169 - loss: 0.2109 - val_accuracy: 0.7013 - val_loss: 0.7812
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9283 - loss: 0.2034 - val_accuracy: 0.7208 - val_loss: 0.8110
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9300 - loss: 0.1981 - val_accuracy: 0.6883 - val_loss: 0.8893
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9267 - loss: 0.2013 - val_accuracy: 0.7338 - val_loss: 0.8117
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9316 - loss: 0.1896 - val_accuracy: 0.7013 - val_loss: 0.8475
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9283 - loss: 0.1850 - val_accuracy: 0.7078 - val_loss: 0.8802
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9446 - loss: 0.1783 - val_accuracy: 0.6883 - val_loss: 0.9185
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9430 - loss: 0.1713 - val_accuracy: 0.6948 - val_loss: 0.8706
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9479 - loss: 0.1668 - val_accuracy: 0.6818 - val_loss: 0.9299
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9446 - loss: 0.1732 - val_accuracy: 0.7078 - val_loss: 0.9675
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9495 - loss: 0.1520 - val_accuracy: 0.6818 - val_loss: 0.9571
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9349 - loss: 0.1566 - val_accuracy: 0.6429 - val_loss: 1.0294
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9511 - loss: 0.1572 - val_accuracy: 0.7143 - val_loss: 0.9705
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9544 - loss: 0.1389 - val_accuracy: 0.6364 - val_loss: 1.1547
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9544 - loss: 0.1400 - val_accuracy: 0.7143 - val_loss: 0.9069
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9495 - loss: 0.1443 - val_accuracy: 0.6623 - val_loss: 1.1276
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9560 - loss: 0.1365 - val_accuracy: 0.6948 - val_loss: 1.1638
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9625 - loss: 0.1272 - val_accuracy: 0.7013 - val_loss: 1.0573
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9625 - loss: 0.1240 - val_accuracy: 0.7013 - val_loss: 1.0441
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9625 - loss: 0.1197 - val_accuracy: 0.6623 - val_loss: 1.1158
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9625 - loss: 0.1200 - val_accuracy: 0.6688 - val_loss: 1.0856
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9609 - loss: 0.1168 - val_accuracy: 0.6883 - val_loss: 1.2479
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9658 - loss: 0.1111 - val_accuracy: 0.6818 - val_loss: 1.1345
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9625 - loss: 0.1074 - val_accuracy: 0.7208 - val_loss: 1.2794
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9674 - loss: 0.1042 - val_accuracy: 0.6753 - val_loss: 1.1873
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9658 - loss: 0.1013 - val_accuracy: 0.6948 - val_loss: 1.4609
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9691 - loss: 0.0975 - val_accuracy: 0.7078 - val_loss: 1.3399
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9756 - loss: 0.0891 - val_accuracy: 0.6948 - val_loss: 1.2985
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9756 - loss: 0.0861 - val_accuracy: 0.6948 - val_loss: 1.2835
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9739 - loss: 0.0909 - val_accuracy: 0.7013 - val_loss: 1.3931
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9674 - loss: 0.0890 - val_accuracy: 0.7013 - val_loss: 1.2882
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9788 - loss: 0.0809 - val_accuracy: 0.7013 - val_loss: 1.3950
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9723 - loss: 0.0850 - val_accuracy: 0.7143 - val_loss: 1.3501
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9805 - loss: 0.0763 - val_accuracy: 0.6948 - val_loss: 1.4300
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9756 - loss: 0.0851 - val_accuracy: 0.6948 - val_loss: 1.3244
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9772 - loss: 0.0664 - val_accuracy: 0.6883 - val_loss: 1.3216
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9756 - loss: 0.0792 - val_accuracy: 0.6948 - val_loss: 1.5123
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9821 - loss: 0.0622 - val_accuracy: 0.6623 - val_loss: 1.5187
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9772 - loss: 0.0695 - val_accuracy: 0.7208 - val_loss: 1.4832
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9805 - loss: 0.0652 - val_accuracy: 0.7013 - val_loss: 1.4391
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9821 - loss: 0.0664 - val_accuracy: 0.6883 - val_loss: 1.4260
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9837 - loss: 0.0600 - val_accuracy: 0.7078 - val_loss: 1.4910
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9886 - loss: 0.0495 - val_accuracy: 0.6299 - val_loss: 1.9771
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9788 - loss: 0.0617 - val_accuracy: 0.6883 - val_loss: 1.5272
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9902 - loss: 0.0483 - val_accuracy: 0.6753 - val_loss: 1.5303
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9756 - loss: 0.0630 - val_accuracy: 0.7273 - val_loss: 1.5118
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9902 - loss: 0.0430 - val_accuracy: 0.7078 - val_loss: 1.5749

### tuning multiple params

In [172]:
import keras
from keras import layers, Sequential

def build_model(hp):
    model = Sequential()

    # 1. Define number of layers to tune
    num_layers = hp.Int('num_layers', min_value=1, max_value=10)

    for i in range(num_layers):
        # 2. Add Dense layer with tunable units and activation
        # Note: 'input_shape' is only needed for the very first layer
        if i == 0:
            model.add(layers.Dense(
                units=hp.Int(f'units_{i}', min_value=8, max_value=128, step=8),
                activation=hp.Choice(f'activation_{i}', values=['relu', 'tanh', 'sigmoid']),
                input_shape=(8,)
            ))
        else:
            model.add(layers.Dense(
                units=hp.Int(f'units_{i}', min_value=8, max_value=128, step=8),
                activation=hp.Choice(f'activation_{i}', values=['relu', 'tanh', 'sigmoid'])
            ))

        # 3. Add Tunable Dropout after each Dense layer
        model.add(layers.Dropout(
            rate=hp.Choice(f'dropout_{i}', values=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])
        ))

    # 4. Final Output Layer for binary classification
    model.add(layers.Dense(1, activation='sigmoid'))

    # 5. Tunable Optimizer
    model.compile(
        optimizer=hp.Choice('optimizer', values=['rmsprop', 'adam', 'sgd', 'nadam', 'adadelta']),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )
    return model

In [173]:
tuner = kt.RandomSearch(build_model, objective='val_accuracy', max_trials=3, directory='mydir', project_name='final1')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [174]:
tuner.search(x_train, y_train, epochs = 5, validation_data = (x_test, y_test))

Trial 3 Complete [00h 00m 13s]
val_accuracy: 0.649350643157959

Best val_accuracy So Far: 0.649350643157959
Total elapsed time: 00h 00m 34s

In [175]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 8,
 'units_0': 104,
 'activation_0': 'sigmoid',
 'dropout_0': 0.5,
 'optimizer': 'adam',
 'units_1': 8,
 'activation_1': 'relu',
 'dropout_1': 0.1,
 'units_2': 8,
 'activation_2': 'relu',
 'dropout_2': 0.1,
 'units_3': 8,
 'activation_3': 'relu',
 'dropout_3': 0.1,
 'units_4': 8,
 'activation_4': 'relu',
 'dropout_4': 0.1,
 'units_5': 8,
 'activation_5': 'relu',
 'dropout_5': 0.1,
 'units_6': 8,
 'activation_6': 'relu',
 'dropout_6': 0.1,
 'units_7': 8,
 'activation_7': 'relu',
 'dropout_7': 0.1}

In [176]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 38 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [177]:
model.fit(x_train, y_train, epochs = 200, initial_epoch=6, validation_data=(x_test, y_test))

Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 12s 228ms/step - accuracy: 0.6433 - loss: 0.6809 - val_accuracy: 0.6494 - val_loss: 0.6765
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6531 - loss: 0.6712 - val_accuracy: 0.6494 - val_loss: 0.6620
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6466 - loss: 0.6656 - val_accuracy: 0.6494 - val_loss: 0.6491
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6498 - loss: 0.6469 - val_accuracy: 0.6494 - val_loss: 0.6393
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6498 - loss: 0.6589 - val_accuracy: 0.6494 - val_loss: 0.6344
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6498 - loss: 0.6454 - val_accuracy: 0.6494 - val_loss: 0.6255
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6482 - loss: 0.6343 - val_accuracy: 0.6494 - val_loss: 0.6126
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6498 - loss: 0.6397 - val_accuracy: 0.6494 - val_loss: 0.6070
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6515 - loss: 0.6311 - val_accuracy: 0.6494 - val_loss: 0.5973
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6482 - loss: 0.6296 - val_accuracy: 0.6494 - val_loss: 0.5926
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6515 - loss: 0.6249 - val_accuracy: 0.6494 - val_loss: 0.5863
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6515 - loss: 0.6030 - val_accuracy: 0.6494 - val_loss: 0.5732
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6498 - loss: 0.6048 - val_accuracy: 0.6494 - val_loss: 0.5654
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6498 - loss: 0.5930 - val_accuracy: 0.6494 - val_loss: 0.5586
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6531 - loss: 0.5953 - val_accuracy: 0.6494 - val_loss: 0.5555
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6515 - loss: 0.5965 - val_accuracy: 0.6494 - val_loss: 0.5533
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6515 - loss: 0.5905 - val_accuracy: 0.6494 - val_loss: 0.5478
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6515 - loss: 0.5833 - val_accuracy: 0.6494 - val_loss: 0.5478
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6515 - loss: 0.5875 - val_accuracy: 0.6494 - val_loss: 0.5530
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6515 - loss: 0.5744 - val_accuracy: 0.6494 - val_loss: 0.5449
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6515 - loss: 0.5743 - val_accuracy: 0.6494 - val_loss: 0.5433
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.5739 - val_accuracy: 0.6494 - val_loss: 0.5473
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6515 - loss: 0.5644 - val_accuracy: 0.6494 - val_loss: 0.5398
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6515 - loss: 0.5779 - val_accuracy: 0.6494 - val_loss: 0.5423
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6515 - loss: 0.5694 - val_accuracy: 0.6494 - val_loss: 0.5416
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6515 - loss: 0.5433 - val_accuracy: 0.6494 - val_loss: 0.5431
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6515 - loss: 0.5786 - val_accuracy: 0.6494 - val_loss: 0.5396
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6515 - loss: 0.5727 - val_accuracy: 0.6494 - val_loss: 0.5401
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6515 - loss: 0.5474 - val_accuracy: 0.6494 - val_loss: 0.5381
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6515 - loss: 0.5667 - val_accuracy: 0.6494 - val_loss: 0.5384
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6515 - loss: 0.5741 - val_accuracy: 0.6494 - val_loss: 0.5404
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6515 - loss: 0.5528 - val_accuracy: 0.6494 - val_loss: 0.5386
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6515 - loss: 0.5454 - val_accuracy: 0.6494 - val_loss: 0.5379
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6498 - loss: 0.5453 - val_accuracy: 0.6494 - val_loss: 0.5381
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6515 - loss: 0.5372 - val_accuracy: 0.6494 - val_loss: 0.5384
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6498 - loss: 0.5373 - val_accuracy: 0.7532 - val_loss: 0.5396
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7362 - loss: 0.5513 - val_accuracy: 0.7468 - val_loss: 0.5384
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7199 - loss: 0.5584 - val_accuracy: 0.7597 - val_loss: 0.5379
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7068 - loss: 0.5717 - val_accuracy: 0.7532 - val_loss: 0.5380
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7264 - loss: 0.5598 - val_accuracy: 0.7597 - val_loss: 0.5434
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7085 - loss: 0.5452 - val_accuracy: 0.7532 - val_loss: 0.5370
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7248 - loss: 0.5429 - val_accuracy: 0.7597 - val_loss: 0.5380
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7345 - loss: 0.5342 - val_accuracy: 0.7403 - val_loss: 0.5381
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7134 - loss: 0.5535 - val_accuracy: 0.7143 - val_loss: 0.5384
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7264 - loss: 0.5341 - val_accuracy: 0.7078 - val_loss: 0.5357
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7101 - loss: 0.5502 - val_accuracy: 0.7013 - val_loss: 0.5322
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7508 - loss: 0.5444 - val_accuracy: 0.7078 - val_loss: 0.5349
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7378 - loss: 0.5383 - val_accuracy: 0.7078 - val_loss: 0.5351
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7345 - loss: 0.5351 - val_accuracy: 0.7143 - val_loss: 0.5363
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7280 - loss: 0.5468 - val_accuracy: 0.7078 - val_loss: 0.5344
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7085 - loss: 0.5547 - val_accuracy: 0.7078 - val_loss: 0.5338
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7248 - loss: 0.5459 - val_accuracy: 0.7143 - val_loss: 0.5347
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7052 - loss: 0.5527 - val_accuracy: 0.7078 - val_loss: 0.5352
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7590 - loss: 0.5207 - val_accuracy: 0.7143 - val_loss: 0.5343
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7199 - loss: 0.5377 - val_accuracy: 0.7273 - val_loss: 0.5362
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7524 - loss: 0.5311 - val_accuracy: 0.7468 - val_loss: 0.5363
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7394 - loss: 0.5294 - val_accuracy: 0.7597 - val_loss: 0.5364
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7264 - loss: 0.5380 - val_accuracy: 0.7338 - val_loss: 0.5358
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7296 - loss: 0.5238 - val_accuracy: 0.7273 - val_loss: 0.5353
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7492 - loss: 0.5426 - val_accuracy: 0.7208 - val_loss: 0.5363
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7524 - loss: 0.5355 - val_accuracy: 0.7597 - val_loss: 0.5345
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7345 - loss: 0.5345 - val_accuracy: 0.7532 - val_loss: 0.5353
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7476 - loss: 0.5403 - val_accuracy: 0.7273 - val_loss: 0.5365
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7508 - loss: 0.5087 - val_accuracy: 0.7273 - val_loss: 0.5351
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7508 - loss: 0.5276 - val_accuracy: 0.7078 - val_loss: 0.5383
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7362 - loss: 0.5402 - val_accuracy: 0.7208 - val_loss: 0.5348
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7476 - loss: 0.5426 - val_accuracy: 0.7208 - val_loss: 0.5359
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7541 - loss: 0.5343 - val_accuracy: 0.7143 - val_loss: 0.5397
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7524 - loss: 0.5272 - val_accuracy: 0.7468 - val_loss: 0.5345
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7329 - loss: 0.5364 - val_accuracy: 0.7273 - val_loss: 0.5353
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7345 - loss: 0.5239 - val_accuracy: 0.7143 - val_loss: 0.5376
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7492 - loss: 0.5287 - val_accuracy: 0.7273 - val_loss: 0.5349
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7427 - loss: 0.5404 - val_accuracy: 0.7143 - val_loss: 0.5342
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7329 - loss: 0.5281 - val_accuracy: 0.7078 - val_loss: 0.5344
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7476 - loss: 0.5392 - val_accuracy: 0.7078 - val_loss: 0.5355
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7476 - loss: 0.5197 - val_accuracy: 0.7078 - val_loss: 0.5361
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7443 - loss: 0.5335 - val_accuracy: 0.7143 - val_loss: 0.5338
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7362 - loss: 0.5480 - val_accuracy: 0.7078 - val_loss: 0.5378
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7622 - loss: 0.5359 - val_accuracy: 0.7208 - val_loss: 0.5368
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7476 - loss: 0.5258 - val_accuracy: 0.7273 - val_loss: 0.5334
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7573 - loss: 0.5093 - val_accuracy: 0.7273 - val_loss: 0.5350
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7378 - loss: 0.5264 - val_accuracy: 0.7273 - val_loss: 0.5386
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7573 - loss: 0.5293 - val_accuracy: 0.7662 - val_loss: 0.5335
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7524 - loss: 0.5165 - val_accuracy: 0.7597 - val_loss: 0.5325
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7427 - loss: 0.5327 - val_accuracy: 0.7532 - val_loss: 0.5327
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7410 - loss: 0.5116 - val_accuracy: 0.7403 - val_loss: 0.5325
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7541 - loss: 0.5219 - val_accuracy: 0.7532 - val_loss: 0.5313
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7459 - loss: 0.5299 - val_accuracy: 0.7338 - val_loss: 0.5330
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7329 - loss: 0.5124 - val_accuracy: 0.7403 - val_loss: 0.5330
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7508 - loss: 0.5006 - val_accuracy: 0.7338 - val_loss: 0.5306
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7394 - loss: 0.4952 - val_accuracy: 0.7403 - val_loss: 0.5308
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7329 - loss: 0.5370 - val_accuracy: 0.7273 - val_loss: 0.5331
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7264 - loss: 0.5380 - val_accuracy: 0.7208 - val_loss: 0.5335
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7638 - loss: 0.5131 - val_accuracy: 0.7403 - val_loss: 0.5291
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7427 - loss: 0.5297 - val_accuracy: 0.7208 - val_loss: 0.5331
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7362 - loss: 0.5195 - val_accuracy: 0.7208 - val_loss: 0.5329
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7427 - loss: 0.5117 - val_accuracy: 0.7338 - val_loss: 0.5295
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7378 - loss: 0.5211 - val_accuracy: 0.7208 - val_loss: 0.5307
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7492 - loss: 0.5338 - val_accuracy: 0.7208 - val_loss: 0.5307
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7345 - loss: 0.5249 - val_accuracy: 0.7208 - val_loss: 0.5303
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7264 - loss: 0.5283 - val_accuracy: 0.7273 - val_loss: 0.5283
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7557 - loss: 0.5156 - val_accuracy: 0.7208 - val_loss: 0.5277
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7362 - loss: 0.5248 - val_accuracy: 0.7143 - val_loss: 0.5320
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7410 - loss: 0.5202 - val_accuracy: 0.7208 - val_loss: 0.5283
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7378 - loss: 0.5237 - val_accuracy: 0.7273 - val_loss: 0.5275
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7687 - loss: 0.5248 - val_accuracy: 0.7273 - val_loss: 0.5314
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7622 - loss: 0.5105 - val_accuracy: 0.7532 - val_loss: 0.5267
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7606 - loss: 0.5247 - val_accuracy: 0.7338 - val_loss: 0.5311
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7508 - loss: 0.5094 - val_accuracy: 0.7338 - val_loss: 0.5274
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7671 - loss: 0.5059 - val_accuracy: 0.7403 - val_loss: 0.5272
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7459 - loss: 0.5254 - val_accuracy: 0.7273 - val_loss: 0.5274
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7508 - loss: 0.5293 - val_accuracy: 0.7208 - val_loss: 0.5289
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7492 - loss: 0.5181 - val_accuracy: 0.7338 - val_loss: 0.5263
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7622 - loss: 0.5013 - val_accuracy: 0.7208 - val_loss: 0.5304
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7687 - loss: 0.5113 - val_accuracy: 0.7338 - val_loss: 0.5275
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7687 - loss: 0.5081 - val_accuracy: 0.7338 - val_loss: 0.5245
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7443 - loss: 0.5378 - val_accuracy: 0.7338 - val_loss: 0.5296
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7622 - loss: 0.5069 - val_accuracy: 0.7338 - val_loss: 0.5272
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7704 - loss: 0.5230 - val_accuracy: 0.7338 - val_loss: 0.5254
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7573 - loss: 0.5188 - val_accuracy: 0.7273 - val_loss: 0.5290
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7378 - loss: 0.5078 - val_accuracy: 0.7468 - val_loss: 0.5266
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7394 - loss: 0.5332 - val_accuracy: 0.7338 - val_loss: 0.5260
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7557 - loss: 0.5002 - val_accuracy: 0.7338 - val_loss: 0.5243
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7280 - loss: 0.5306 - val_accuracy: 0.7468 - val_loss: 0.5276
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7296 - loss: 0.5223 - val_accuracy: 0.7403 - val_loss: 0.5255
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7524 - loss: 0.5094 - val_accuracy: 0.7338 - val_loss: 0.5218
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7622 - loss: 0.5076 - val_accuracy: 0.7338 - val_loss: 0.5225
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7704 - loss: 0.5123 - val_accuracy: 0.7468 - val_loss: 0.5220
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4983 - val_accuracy: 0.7468 - val_loss: 0.5211
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4909 - val_accuracy: 0.7403 - val_loss: 0.5224
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7606 - loss: 0.4961 - val_accuracy: 0.7338 - val_loss: 0.5229
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7476 - loss: 0.5069 - val_accuracy: 0.7338 - val_loss: 0.5227
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7427 - loss: 0.5149 - val_accuracy: 0.7338 - val_loss: 0.5266
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7541 - loss: 0.5161 - val_accuracy: 0.7662 - val_loss: 0.5198
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.5153 - val_accuracy: 0.7468 - val_loss: 0.5221
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7752 - loss: 0.5059 - val_accuracy: 0.7662 - val_loss: 0.5195
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7606 - loss: 0.4998 - val_accuracy: 0.7662 - val_loss: 0.5187
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7573 - loss: 0.5116 - val_accuracy: 0.7727 - val_loss: 0.5226
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7590 - loss: 0.5220 - val_accuracy: 0.7727 - val_loss: 0.5210
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7606 - loss: 0.5135 - val_accuracy: 0.7597 - val_loss: 0.5248
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7541 - loss: 0.5030 - val_accuracy: 0.7792 - val_loss: 0.5163
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7443 - loss: 0.5055 - val_accuracy: 0.7597 - val_loss: 0.5183
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7655 - loss: 0.5102 - val_accuracy: 0.7727 - val_loss: 0.5181
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7687 - loss: 0.5041 - val_accuracy: 0.7662 - val_loss: 0.5191
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7736 - loss: 0.4923 - val_accuracy: 0.7403 - val_loss: 0.5199
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7622 - loss: 0.5194 - val_accuracy: 0.7403 - val_loss: 0.5217
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7590 - loss: 0.5308 - val_accuracy: 0.7338 - val_loss: 0.5300
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7606 - loss: 0.5112 - val_accuracy: 0.7338 - val_loss: 0.5277
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7638 - loss: 0.5159 - val_accuracy: 0.7532 - val_loss: 0.5215
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7508 - loss: 0.4982 - val_accuracy: 0.7532 - val_loss: 0.5221
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7492 - loss: 0.5105 - val_accuracy: 0.7403 - val_loss: 0.5215
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7655 - loss: 0.5087 - val_accuracy: 0.7597 - val_loss: 0.5233
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7492 - loss: 0.5175 - val_accuracy: 0.7857 - val_loss: 0.5190
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7720 - loss: 0.5128 - val_accuracy: 0.7468 - val_loss: 0.5237
Epoch 161/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7524 - loss: 0.5071 - val_accuracy: 0.7597 - val_loss: 0.5214
Epoch 162/200